name: flutter_webview_plugin_example
description: Demonstrates how to use the flutter_webview_plugin plugin.

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^0.3.22+1

flutter:
  uses-material-design: true
  assets:
   - assets/tr.html
  
